language: php
php:
- 5.5
- 5.6
- hhvm
before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist
- cp .env.example .env
- php artisan key:generate
- touch storage/database.sqlite
- php artisan migrate --force
- php artisan db:seed --force
script:
- phpunit
