# $ docker-compose -f docker-compose-local.yml up -d
# $ docker-compose -f docker-compose-local.yml down
# $ docker-compose -f docker-compose-local.yml stop
db:
  image: percona
  ports:
    - "3306:3306"
  container_name: db_collins_local
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: collins
    MYSQL_PASSWORD: secret
    MYSQL_DATABASE: collins
